# Generated by Django 4.2.5 on 2023-11-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_alter_customuser_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='U_id',
            new_name='id',
        ),
    ]
