# Generated by Django 4.2.5 on 2023-11-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0005_rename_id_customuser_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
