# Generated by Django 4.2.5 on 2023-11-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0006_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userName',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
