# Generated by Django 4.2.5 on 2023-11-27 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0012_remove_customuser_email_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('Q_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titleText', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('viewsNo', models.IntegerField(default=uuid.uuid4)),
                ('likes', models.IntegerField(default=uuid.uuid4)),
                ('dislike', models.IntegerField(default=uuid.uuid4)),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.customuser')),
            ],
        ),
    ]
