# Generated by Django 4.2.5 on 2023-11-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0014_alter_questions_dislike_alter_questions_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
