# Generated by Django 4.2.5 on 2023-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0016_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
