# Generated by Django 4.2.5 on 2023-12-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0019_question_dis_liked_by_question_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dis_liked_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='liked_by',
        ),
    ]
